import * as fs from "node:fs";
import * as path from "node:path";
import { readLedger } from "../lib/ledger";

const HOOK_ADDRESSES_PATH = path.resolve(
  __dirname,
  "../../../src/gasless-intents/interactions/helpers/hook-addresses.ts",
);

const ZERO = "0x0000000000000000000000000000000000000000" as const;

const HOOK_CONTRACTS = [
  "LoggingInteractionHook",
  "FillCounter",
  "ProtocolFeeRecorder",
  "AllowlistGuard",
  "RewardMinter",
  "FillCapEnforcer",
] as const;

function generate(addresses: Record<string, string | null>): string {
  const entries = HOOK_CONTRACTS.map(
    (name) => `  ${name}: "${addresses[name] ?? ZERO}" as Address,`,
  ).join("\n");

  return `import type { Address } from "viem";

/**
 * Addresses of the interaction-hook example contracts on Base mainnet
 * (chainId 8453). Generated by \`solidity/scripts/sync-hook-addresses.ts\`
 * from \`solidity/build-artefacts/deployed-base.json\`. Do not edit by hand —
 * redeploy and re-run the sync script instead.
 *
 * If you fork this repo, you must redeploy and overwrite these values — the
 * Intent Manager calls hooks by address with no further authentication, so
 * any address here is trusted to receive your interaction calldata.
 */
export const HOOK_ADDRESSES = {
${entries}
} as const;

export type HookName = keyof typeof HOOK_ADDRESSES;

export function requireHookAddress(name: HookName): Address {
  const addr = HOOK_ADDRESSES[name];
  if (addr === "${ZERO}") {
    throw new Error(
      \`\${name} address not set in helpers/hook-addresses.ts \\u2014 deploy via \` +
        \`solidity/scripts/deploy-\${kebabCase(name)}.ts then run \` +
        \`solidity/scripts/sync-hook-addresses.ts.\`,
    );
  }
  return addr;
}

function kebabCase(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}
`;
}

function main(): void {
  const ledger = readLedger();
  const addresses: Record<string, string | null> = {};
  for (const name of HOOK_CONTRACTS) {
    const entry = ledger.contracts[name];
    addresses[name] = entry?.address ?? null;
  }

  const content = generate(addresses);
  fs.writeFileSync(HOOK_ADDRESSES_PATH, content);

  console.log(`Wrote ${path.relative(process.cwd(), HOOK_ADDRESSES_PATH)}:`);
  for (const name of HOOK_CONTRACTS) {
    console.log(`  ${name}: ${addresses[name] ?? `${ZERO} (not deployed)`}`);
  }
  console.log("\nReview the diff before committing.");
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}
